workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20
    scripts:
      - name: Install Node.js dependencies
        script: npm install
      - name: Install Capacitor dependencies
        script: npm install @capacitor/android @capacitor/cli @capacitor/core capacitor-sunmi-printer-v7
      - name: Add Android platform
        script: npx cap add android
      - name: Sync project
        script: npx cap sync
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/**/*.apk